-- Registration email templates: make the emails sent by the
-- send-registration-confirmation edge function editable in Admin → Communications
-- → Templates, alongside the existing bulk-email templates.
--
-- System templates are identified by `template_key` (custom templates keep it
-- null). The edge function looks templates up by key, so admins can't break the
-- wiring by renaming; the admin UI locks the name and hides Delete for these rows.
-- Keys: registration_confirmation, registration_group_summary, registration_rules.
--
-- Dynamic content ({{events_table}}, {{payment_section}}, {{group_table}},
-- {{tbd_note}}, {{rules_body}}, ...) is generated by the edge function at send
-- time; the templates control the prose around those blocks. If a template row is
-- missing or its body is blanked, the edge function falls back to the same
-- defaults hardcoded in its DEFAULT_TEMPLATES — so this migration is safe to run
-- before or after deploying the function.
--
-- Idempotent: seeds insert only when the key doesn't exist yet, so re-running
-- never overwrites admin edits. Runnable via `supabase db push` or pasted into
-- the dashboard SQL editor.

alter table public.email_templates
  add column if not exists template_key text;

create unique index if not exists email_templates_template_key_key
  on public.email_templates (template_key)
  where template_key is not null;

-- The edge function reads rules + resolves the tournament year via the service
-- role; raw-SQL tables in this project need explicit grants for that role.
grant select on public.tournament_rules to service_role;
grant select on public.tournaments to service_role;

-- Individual confirmation (solo registrant, or a secondary member of a group).
insert into public.email_templates (name, subject, body_html, template_key)
select
  'Registration confirmation',
  'Your Kathryn Classic {{year}} registration — {{total}} due',
  $html$<h1 style="color:#0d9488;font-size:24px;margin:0 0 8px;">You're registered!</h1>
<p style="font-size:16px;margin:0 0 20px;">
  Hi {{first_name}}, thank you for registering for
  <strong>The Kathryn Classic {{year}}</strong>.
</p>
{{group_note}}

<h2 style="font-size:16px;margin:24px 0 8px;">What you registered for</h2>
{{events_table}}

{{tbd_note}}

{{payment_section}}

<p style="font-size:13px;color:#777;margin:24px 0 0;">
  Questions? Just reply to this email. We can't wait to see you at the tournament!
</p>$html$,
  'registration_confirmation'
where not exists (
  select 1 from public.email_templates where template_key = 'registration_confirmation'
);

-- Group summary sent to the organizer (first attendee) of a group registration.
insert into public.email_templates (name, subject, body_html, template_key)
select
  'Registration group summary',
  'Your Kathryn Classic {{year}} group registration — {{group_total}} total',
  $html$<h1 style="color:#0d9488;font-size:24px;margin:0 0 8px;">You're all registered!</h1>
<p style="font-size:16px;margin:0 0 20px;">
  Hi {{first_name}}, thanks for registering your group for
  <strong>The Kathryn Classic {{year}}</strong>.
  Here's a summary for everyone you signed up.
</p>

<h2 style="font-size:16px;margin:24px 0 8px;">Your group</h2>
{{group_table}}

{{payment_section}}

<p style="font-size:13px;color:#777;margin:24px 0 0;">
  Questions? Just reply to this email. We can't wait to see you all at the tournament!
</p>$html$,
  'registration_group_summary'
where not exists (
  select 1 from public.email_templates where template_key = 'registration_group_summary'
);

-- Tournament rules email, sent to every registrant right after their confirmation.
-- {{rules_body}} is the year's tournament_rules.body_html (managed in Admin → Rules).
insert into public.email_templates (name, subject, body_html, template_key)
select
  'Registration rules email',
  'Tournament rules — The Kathryn Classic {{year}}',
  $html$<h1 style="color:#0d9488;font-size:24px;margin:0 0 8px;">Tournament rules</h1>
<p style="font-size:16px;margin:0 0 20px;">
  Hi {{first_name}}, here are the rules for
  <strong>The Kathryn Classic {{year}}</strong>. Give them a quick read before tournament day.
</p>
{{rules_body}}
<p style="font-size:13px;color:#777;margin:24px 0 0;">
  Questions? Just reply to this email. See you out there!
</p>$html$,
  'registration_rules'
where not exists (
  select 1 from public.email_templates where template_key = 'registration_rules'
);
